name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # for Workload Identity Federation

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & push image to AR
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          REPO=quote-app
          IMG=us-central1-docker.pkg.dev/${PROJECT_ID}/${REPO}/backend-app
          docker build -t $IMG:latest -t $IMG:${{ github.sha }} .
          docker push $IMG:latest
          docker push $IMG:${{ github.sha }}
          echo "IMAGE=$IMG:${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image="${IMAGE}" \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
